export type Locale = "en" | "zh-Hant" | "zh-Hans" | "ta" | "ms";

export const locales: Locale[] = ["en", "zh-Hant", "zh-Hans", "ta", "ms"];

export const localeLabels: Record<Locale, string> = {
  en: "EN",
  "zh-Hant": "繁體",
  "zh-Hans": "简体",
  ta: "த",
  ms: "MY",
};

export const localeNames: Record<Locale, string> = {
  en: "English",
  "zh-Hant": "繁體中文",
  "zh-Hans": "简体中文",
  ta: "தமிழ்",
  ms: "Bahasa Melayu",
};

type Category = "Advanced" | "Intermediate" | "Standing" | "Sitting" | "Interview";

const englishTermsUi = {
  termsEyebrow: "Legal",
  termsTitleLine1: "Terms & Conditions",
  termsTitleLine2: "and right of use statement",
  termsLastUpdated: "Last updated 22 September 2026",
  termsSection1Title: "1. About this project",
  termsSection1Body:
    "Heal Yoga is an academic, non-commercial project created by a University of Glasgow Singapore and Singapore Institute of Technology student team (CSC2101 & CSC2102) as part of a Professional Software Development and Team Project module. It is provided for educational, research, and public-benefit purposes only.",
  termsSection2Title: "2. Not medical advice — your safety is your responsibility",
  termsSection2Body:
    "The yoga poses, stretches, and exercises demonstrated on this site are general wellness content, not medical advice. You are solely responsible for your own health and safety when following any content on this site. Please consult a qualified doctor or healthcare professional before starting any new exercise programme, particularly if you are pregnant, elderly, recovering from an injury, or have any pre-existing medical condition. Stop immediately and seek medical attention if you feel pain, dizziness, or discomfort.",
  termsSection3Title: "3. No warranty on accuracy",
  termsSection3Body:
    "While we have made our best effort to ensure the information, instructions, and content on this site are accurate and safe, we do not warrant or guarantee the completeness, accuracy, reliability, or suitability of any content for any particular purpose. Heal Yoga is provided “as is” and “as available”, without warranties of any kind, express or implied.",
  termsSection4Title: "4. Limitation of liability",
  termsSection4Body:
    "To the fullest extent permitted by law, the Heal Yoga project team, its student developers, faculty advisor, contributing instructors, and affiliated institutions accept no liability or responsibility for any injury, loss, damage, or adverse outcome — direct or indirect — arising from your use of, or reliance on, this site or its content. You use Heal Yoga entirely at your own risk.",
  termsSection5Title: "5. Right of use and content ownership",
  termsSection5Body:
    "Video demonstrations, interviews, and photographs featured on this site are used with the informed consent of the individuals shown, for the educational purposes of this project. The underlying application source code is published as open source on GitHub for academic and non-commercial reuse (see the project repository for licence details); this does not extend to the personal likeness, voice, or image of any individual appearing in the videos or photographs, which may not be reused, copied, or redistributed separately without permission. All third-party video content is embedded via YouTube and remains subject to YouTube's own terms of service.",
  termsSection6Title: "6. Changes to these terms",
  termsSection6Body:
    "We may update this page from time to time as the project evolves. Continued use of Heal Yoga after changes are posted constitutes acceptance of the revised terms.",
  termsSection7Title: "7. Contact",
  termsSection7Body:
    "Questions about this statement can be directed to the faculty advisor via the GitHub project page linked in Credits.",
  termsSection8Title: "8. Language and translations",
  termsSection8Body:
    "English is the original and authoritative language of this site. All other languages offered (繁體中文, 简体中文, Bahasa Melayu, தமிழ்) are generated by machine translation and have not been reviewed by a human translator. Machine-translated text may contain errors, omissions, or mistranslations, and should not be relied upon for medical, safety, or legal decisions. In the event of any discrepancy, the English version prevails.",
};

export const ui: Record<Locale, Record<string, string>> = {
  en: {
    navPractice: "Practice",
    navInterviews: "Interviews",
    navCredits: "Credits",
    brandHome: "Heal Yoga home",

    heroEyebrow: "Movement for every body",
    heroTitleLine1: "Find your balance,",
    heroTitleLine2: "one pose at a time.",
    heroBody: "Accessible, instructor-led yoga demonstrations designed for students, older adults, and everyone beginning their wellness journey.",
    heroCta: "Explore 22 practices",

    libraryEyebrow: "Guided library",
    libraryTitle: "Choose your practice",
    searchPlaceholder: "Search poses",
    searchAriaLabel: "Search yoga poses",
    filtersAriaLabel: "Filter by practice type",
    emptyResults: "No poses match your search. Try a different term.",

    interviewsEyebrow: "Conversations on wellbeing",
    interviewsTitleLine1: "Hear from the people",
    interviewsTitleLine2: "behind the practice.",
    interviewsBody: "Short perspectives from clinical and yoga professionals on accessible movement, healthy ageing, and the thinking behind Heal Yoga.",
    nowPlaying: "Now playing",
    playInterview: "Play interview",

    writtenPhotoName: "A/Prof Kamala Devi",
    writtenPhotoAffiliation1: "School of Medicine, Dentistry & Nursing",
    writtenPhotoAffiliation2: "University of Glasgow",
    writtenEyebrow: "In her own words",
    writtenTitle: "A nursing perspective on Heal Yoga",
    writtenP1: "The objectives of launching this app are to help seniors build a foundation in yoga practice; help them turn their practice into a habit; help them strengthen their body, calm their mind and feel happy through regular practice.",
    writtenP2: "There are numerous yoga poses. This app highlights a few well-known and accessible poses for seniors, as it is crucial for seniors to learn useful poses while ensuring the poses are not too difficult to follow.",
    writtenP3: "The term “seniors” is used loosely here: it can mean retirees; people who have reached the retirement age but are working; people who have not hit the retirement age but choose to step down; or working adults who feel that they lack the stamina to exercise but want to try out yoga.",
    writtenP4: "This app contains chair yoga poses for beginners, as well as intermediate and advanced poses on the mat. As this app caters to seniors who do self-practice without guidance, the poses are kept simple and accessible. The sequence is designed so seniors get to warm up, do the poses and cool down. The poses aim to provide stretching, muscle strengthening, cardio training, balancing and breath work, and cover the sagittal, frontal and transverse planes of motion so practice is well covered in all directions.",
    writtenP5: "An important reminder for seniors using this app is to breathe deeply and calmly during their practice, which is the essence of yoga. Regular yoga practice helps to strengthen the body, align posture, calm the mind, focus better, improve endurance and promote positive living.",
    writtenContentHeading: "Content",
    writtenContentChairLabel: "Chair yoga (beginner’s level)",
    writtenContentChairBody: " — Practising with a chair helps seniors ease into poses they find challenging and stay in the pose longer to reap its benefits. Chair yoga is highly recommended when ground practice is inaccessible or impractical.",
    writtenContentSunLabel: "Sun salutation (intermediate and advanced level)",
    writtenContentSunBody: " — An important flow sequence in yoga asana which promotes spine health, shoulders and chest opening, and limbs and core strength. It can be used as a warm-up once seniors become familiar with the poses; intermediate level focuses on isolated poses while advanced level focuses on the flow sequence and cardio training.",
    writtenFeaturesHeading: "App features",
    writtenFeaturesBody: "To encourage regular and frequent practice, the app helps seniors track their progress by showing their weekly cumulative practice duration. Once a milestone is reached, they receive a trophy. We also track how seniors feel by asking a number of questions after a month of practice, to increase their body awareness.",
    writtenNursingHeading: "A nursing standpoint",
    writtenNursingBody: "Regular yoga practice offers multidimensional health benefits that are particularly relevant for seniors. Physiologically, yoga enhances musculoskeletal strength, joint mobility, and balance, thereby reducing the risk of falls, a major concern in geriatric care. Controlled breathing and mindful movement improve cardiopulmonary endurance and support better management of chronic conditions such as hypertension, diabetes, and arthritis. Psychologically, yoga fosters relaxation, reduces anxiety, and promotes emotional resilience, which is essential for maintaining mental wellbeing in later life. Importantly, yoga encourages self-efficacy and active participation in health maintenance, aligning with nursing goals of empowering individuals to take ownership of their health and promoting holistic, person-centred care.",

    creditsEyebrow: "A university collaboration",
    creditsTitleLine1: "Built with care.",
    creditsTitleLine2: "Shared with purpose.",
    creditsBody: "Heal Yoga is a higher education initiative using open-source mobile technology to make yoga practice and public health awareness more accessible to youth and older adults.",
    devTeamKicker: "Development team",
    devTeamCourse: "Professional Software Development & Team Project",
    facultyAdvisorLabel: "Faculty advisor",
    facultyAdvisorName: "Dr Peter CY Yau",
    facultyAdvisorGithub: "github.com/drpeteryau ↗",
    supportedByLabel: "Supported by",
    supportedByUniversity: "University of Glasgow",
    supportedBySchool1: "School of Computing Science",
    supportedBySchool2: "School of Medicine, Dentistry & Nursing",
    supportedByInstitute: "Singapore Institute of Technology",
    specialThanksLabel: "Special thanks",
    specialThanksName: "Ms Lim Li Peng",
    specialThanksBody:
      "This project simply could not have come together without Ms Lim Li Peng's generous support. As our professional yoga instructor, she gave countless hours to the many rounds of video filming — patiently demonstrating and re-demonstrating every pose, guiding retakes, and sharing her expertise so each movement would be safe and easy to follow. Her time, care, and encouragement carried this project from an idea to something we're genuinely proud of, and we're deeply grateful for it.",
    specialThanksLink: "Visit Ms Lim's yoga workshop ↗",
    openByDesign: "Open by design.",
    openByDesignBody: "Created for learning, wellbeing, and public benefit.",
    viewOnGithub: "View on GitHub ↗",
    repo1Name: "healyoga — this web app",
    repo1Desc:
      "This project. Explores practical uses of generative AI and an account-less web app design, so anyone can start practising immediately with no install and no sign-up.",
    repo2Name: "healyoga-poc — mobile app",
    repo2Desc:
      "Production build by the student team, fulfilling the requirements of the CS2101 & CSC2102 Professional Software Development and Team Project modules. A full-function deployment with user account design, for a progress-tracked yoga training mobile hybrid app.",
    ...englishTermsUi,

    footerTagline: "Move gently. Breathe freely. Practice safely.",
    footerAttribution: "University of Glasgow · Academic project",
    footerTerms: "Terms & Conditions",
    termsOnlyNotice: "",

    languageLabel: "Language",

    disclaimerTitle: "Before you begin",
    disclaimerPoint1: "This is a student learning and teaching project, created for educational purposes.",
    disclaimerPoint2: "We do our best to keep the content accurate, but we cannot guarantee that all information is correct.",
    disclaimerPoint3: "Languages other than English are machine-translated and may contain errors.",
    disclaimerPoint4: "Please be mindful of your own safety, and you are responsible for yourself when following any content on this site.",
    disclaimerRemember: "Remember my choice for this session",
    disclaimerAgree: "I Agree, Continue",
    disclaimerDisagree: "I Disagree",
  },
  "zh-Hant": {
    navPractice: "練習",
    navInterviews: "訪談",
    navCredits: "製作團隊",
    brandHome: "回到 Heal Yoga 首頁",

    heroEyebrow: "適合每一種體態的運動",
    heroTitleLine1: "找回你的平衡，",
    heroTitleLine2: "從每一個體式開始。",
    heroBody: "由專業教練示範、簡單易懂的瑜伽練習，專為學生、年長者，以及每一位剛踏上健康旅程的人而設計。",
    heroCta: "探索 22 個練習",

    libraryEyebrow: "引導式影片庫",
    libraryTitle: "選擇你的練習",
    searchPlaceholder: "搜尋體式",
    searchAriaLabel: "搜尋瑜伽體式",
    filtersAriaLabel: "依練習類型篩選",
    emptyResults: "找不到符合搜尋的體式，請嘗試其他關鍵字。",

    interviewsEyebrow: "關於健康的對話",
    interviewsTitleLine1: "聆聽這些人的分享，",
    interviewsTitleLine2: "看見練習背後的故事。",
    interviewsBody: "來自臨床與瑜伽專業人士的簡短分享，談論無障礙運動、健康老化，以及 Heal Yoga 背後的理念。",
    nowPlaying: "現正播放",
    playInterview: "播放訪談",

    writtenPhotoName: "A/Prof Kamala Devi",
    writtenPhotoAffiliation1: "醫學、牙科與護理學院",
    writtenPhotoAffiliation2: "格拉斯哥大學",
    writtenEyebrow: "她的第一手分享",
    writtenTitle: "從護理角度看 Heal Yoga",
    writtenP1: "推出這款應用程式的目的，是協助年長者建立瑜伽練習的基礎，幫助他們把練習變成日常習慣，並透過持續練習強健身體、安定心神、感受快樂。",
    writtenP2: "瑜伽體式種類繁多。這款應用程式精選了幾種廣為人知、容易上手的體式，因為對年長者而言，學習實用且不會太難跟上的體式非常重要。",
    writtenP3: "這裡所說的「年長者」定義較為寬鬆：可以是退休人士；已達退休年齡但仍在工作的人；尚未到退休年齡卻選擇提前退下來的人；或是自覺體力不足以運動、但想嘗試瑜伽的在職人士。",
    writtenP4: "這款應用程式收錄了適合初學者的椅子瑜伽體式，以及在瑜伽墊上進行的中階與進階體式。由於這款應用程式主要提供給無人指導、自行練習的年長者使用，體式設計力求簡單易懂。整套練習依序安排暖身、體式練習與收操。這些體式旨在提供伸展、肌肉強化、心肺訓練、平衡與呼吸練習，並涵蓋矢狀面、額狀面與水平面等多個動作平面，讓練習能全方位兼顧各個方向。",
    writtenP5: "提醒使用這款應用程式的年長者，練習時務必保持深沉、平穩的呼吸，這正是瑜伽的精髓所在。規律的瑜伽練習有助強健身體、端正體態、安定心神、提升專注力、增強耐力，並促進積極正向的生活態度。",
    writtenContentHeading: "內容",
    writtenContentChairLabel: "椅子瑜伽（初學者程度）",
    writtenContentChairBody: " —— 藉助椅子練習，能幫助年長者更容易進入具挑戰性的體式，並延長停留時間以獲得更多效益。當無法在地面練習或不方便這樣做時，特別推薦椅子瑜伽。",
    writtenContentSunLabel: "拜日式（中階與進階程度）",
    writtenContentSunBody: " —— 這是瑜伽體位法中重要的連貫動作序列，有助促進脊椎健康、打開肩胸，並強化四肢與核心力量。當年長者熟悉各個體式後，可作為暖身之用；中階程度著重個別體式，進階程度則著重連貫動作序列與心肺訓練。",
    writtenFeaturesHeading: "應用程式功能",
    writtenFeaturesBody: "為鼓勵規律且頻繁的練習，這款應用程式會顯示每週累積練習時長，協助年長者追蹤進度。達成里程碑後，即可獲得獎盃。我們也會在練習滿一個月後，透過幾個問題了解年長者的感受，提升他們對自己身體狀態的覺察。",
    writtenNursingHeading: "護理角度的觀點",
    writtenNursingBody: "規律的瑜伽練習能帶來多方面的健康效益，對年長者尤其重要。從生理層面來看，瑜伽能增進肌肉骨骼力量、關節活動度與平衡感，進而降低老年照護中特別關注的跌倒風險。控制呼吸與專注的動作有助改善心肺耐力，並協助更妥善地管理高血壓、糖尿病、關節炎等慢性病。從心理層面來看，瑜伽有助放鬆身心、減輕焦慮，並增強情緒韌性，這對維持晚年心理健康至關重要。更重要的是，瑜伽能提升自我效能，鼓勵人們主動參與自身健康管理，呼應護理專業以人為本、賦權個人掌握自身健康的整全照護理念。",

    creditsEyebrow: "大學合作計畫",
    creditsTitleLine1: "用心打造。",
    creditsTitleLine2: "與眾人分享。",
    creditsBody: "Heal Yoga 是一項高等教育計畫，運用開源行動技術，讓瑜伽練習與公共衛生意識更容易觸及青年與年長者。",
    devTeamKicker: "開發團隊",
    devTeamCourse: "專業軟體開發與團隊專案",
    facultyAdvisorLabel: "指導教師",
    facultyAdvisorName: "Dr Peter CY Yau",
    facultyAdvisorGithub: "github.com/drpeteryau ↗",
    supportedByLabel: "支持單位",
    supportedByUniversity: "格拉斯哥大學",
    supportedBySchool1: "電腦科學學院",
    supportedBySchool2: "醫學、牙科與護理學院",
    supportedByInstitute: "新加坡理工學院",
    specialThanksLabel: "特別感謝",
    specialThanksName: "Ms Lim Li Peng",
    specialThanksBody:
      "若沒有林麗萍女士的慷慨支持，這個專案絕不可能完成。身為專業瑜伽導師，她為了多次的影片拍攝付出了無數時間——耐心地一次又一次示範每個體位、配合重拍，並分享她的專業知識，確保每個動作都安全易學。她的時間、用心與鼓勵，讓這個專案從一個構想走到我們如今引以為傲的成果，我們由衷感激。",
    specialThanksLink: "造訪林女士的瑜伽工作坊 ↗",
    openByDesign: "開放，是我們的設計理念。",
    openByDesignBody: "為學習、身心健康與公眾利益而生。",
    viewOnGithub: "在 GitHub 上查看 ↗",
    repo1Name: "healyoga — 本網頁應用",
    repo1Desc:
      "本專案。探索生成式 AI 的實務應用，並採用免帳號設計，讓使用者無需安裝、無需註冊即可立即開始練習。",
    repo2Name: "healyoga-poc — 行動應用程式",
    repo2Desc:
      "由學生團隊開發的正式版本，完成 CS2101 與 CSC2102「專業軟體開發與團隊專案」模組的要求。屬於完整功能部署，具備使用者帳號設計，用於追蹤瑜伽訓練進度的混合式行動應用程式。",
    ...englishTermsUi,

    footerTagline: "輕柔活動身體，自在呼吸，安全練習。",
    footerAttribution: "格拉斯哥大學 · 學術專案",
    footerTerms: "條款及細則",
    termsOnlyNotice: "本頁面（條款及細則與使用權聲明）僅提供英文版本。",

    languageLabel: "語言",

    disclaimerTitle: "開始之前，請先閱讀",
    disclaimerPoint1: "這是一項學生教學專案，僅供教育用途而製作。",
    disclaimerPoint2: "我們已盡力確保內容正確，但無法保證所有資訊皆完全無誤。",
    disclaimerPoint3: "英文以外的語言版本均由機器翻譯產生，可能有誤譯之處。",
    disclaimerPoint4: "使用本網站任何內容時，請留意自身安全，並自行承擔相關責任。",
    disclaimerRemember: "在本次瀏覽期間記住我的選擇",
    disclaimerAgree: "我同意，繼續瀏覽",
    disclaimerDisagree: "我不同意",
  },
  "zh-Hans": {
    navPractice: "练习",
    navInterviews: "访谈",
    navCredits: "制作团队",
    brandHome: "回到 Heal Yoga 首页",

    heroEyebrow: "适合每一种体态的运动",
    heroTitleLine1: "找回你的平衡，",
    heroTitleLine2: "从每一个体式开始。",
    heroBody: "由专业教练示范、简单易懂的瑜伽练习，专为学生、年长者，以及每一位刚踏上健康旅程的人而设计。",
    heroCta: "探索 22 个练习",

    libraryEyebrow: "引导式视频库",
    libraryTitle: "选择你的练习",
    searchPlaceholder: "搜索体式",
    searchAriaLabel: "搜索瑜伽体式",
    filtersAriaLabel: "按练习类型筛选",
    emptyResults: "没有找到符合搜索的体式，请尝试其他关键词。",

    interviewsEyebrow: "关于健康的对话",
    interviewsTitleLine1: "聆听这些人的分享，",
    interviewsTitleLine2: "看见练习背后的故事。",
    interviewsBody: "来自临床与瑜伽专业人士的简短分享，谈论无障碍运动、健康老龄化，以及 Heal Yoga 背后的理念。",
    nowPlaying: "正在播放",
    playInterview: "播放访谈",

    writtenPhotoName: "A/Prof Kamala Devi",
    writtenPhotoAffiliation1: "医学、牙科与护理学院",
    writtenPhotoAffiliation2: "格拉斯哥大学",
    writtenEyebrow: "她的第一手分享",
    writtenTitle: "从护理角度看 Heal Yoga",
    writtenP1: "推出这款应用程序的目的，是帮助年长者建立瑜伽练习的基础，帮助他们把练习变成日常习惯，并通过持续练习强健身体、安定心神、感受快乐。",
    writtenP2: "瑜伽体式种类繁多。这款应用程序精选了几种广为人知、容易上手的体式，因为对年长者而言，学习实用且不会太难跟上的体式非常重要。",
    writtenP3: "这里所说的“年长者”定义较为宽泛：可以是退休人士；已达退休年龄但仍在工作的人；尚未到退休年龄却选择提前退下来的人；或是自觉体力不足以运动、但想尝试瑜伽的在职人士。",
    writtenP4: "这款应用程序收录了适合初学者的椅子瑜伽体式，以及在瑜伽垫上进行的中阶与进阶体式。由于这款应用程序主要提供给无人指导、自行练习的年长者使用，体式设计力求简单易懂。整套练习依序安排热身、体式练习与放松。这些体式旨在提供拉伸、肌肉强化、心肺训练、平衡与呼吸练习，并涵盖矢状面、额状面与水平面等多个动作平面，让练习能全方位兼顾各个方向。",
    writtenP5: "提醒使用这款应用程序的年长者，练习时务必保持深沉、平稳的呼吸，这正是瑜伽的精髓所在。规律的瑜伽练习有助强健身体、端正体态、安定心神、提升专注力、增强耐力，并促进积极正向的生活态度。",
    writtenContentHeading: "内容",
    writtenContentChairLabel: "椅子瑜伽（初学者程度）",
    writtenContentChairBody: " —— 借助椅子练习，能帮助年长者更容易进入具挑战性的体式，并延长停留时间以获得更多益处。当无法在地面练习或不方便这样做时，特别推荐椅子瑜伽。",
    writtenContentSunLabel: "拜日式（中阶与进阶程度）",
    writtenContentSunBody: " —— 这是瑜伽体位法中重要的连贯动作序列，有助促进脊椎健康、打开肩胸，并强化四肢与核心力量。当年长者熟悉各个体式后，可作为热身之用；中阶程度着重个别体式，进阶程度则着重连贯动作序列与心肺训练。",
    writtenFeaturesHeading: "应用程序功能",
    writtenFeaturesBody: "为鼓励规律且频繁的练习，这款应用程序会显示每周累计练习时长，协助年长者追踪进度。达成里程碑后，即可获得奖杯。我们也会在练习满一个月后，通过几个问题了解年长者的感受，提升他们对自己身体状态的觉察。",
    writtenNursingHeading: "护理角度的观点",
    writtenNursingBody: "规律的瑜伽练习能带来多方面的健康益处，对年长者尤其重要。从生理层面来看，瑜伽能增进肌肉骨骼力量、关节活动度与平衡感，进而降低老年照护中特别关注的跌倒风险。控制呼吸与专注的动作有助改善心肺耐力，并协助更妥善地管理高血压、糖尿病、关节炎等慢性病。从心理层面来看，瑜伽有助放松身心、减轻焦虑，并增强情绪韧性，这对维持晚年心理健康至关重要。更重要的是，瑜伽能提升自我效能，鼓励人们主动参与自身健康管理，呼应护理专业以人为本、赋权个人掌握自身健康的整全照护理念。",

    creditsEyebrow: "大学合作计划",
    creditsTitleLine1: "用心打造。",
    creditsTitleLine2: "与众人分享。",
    creditsBody: "Heal Yoga 是一项高等教育计划，运用开源移动技术，让瑜伽练习与公共卫生意识更容易触及青年与年长者。",
    devTeamKicker: "开发团队",
    devTeamCourse: "专业软件开发与团队项目",
    facultyAdvisorLabel: "指导教师",
    facultyAdvisorName: "Dr Peter CY Yau",
    facultyAdvisorGithub: "github.com/drpeteryau ↗",
    supportedByLabel: "支持单位",
    supportedByUniversity: "格拉斯哥大学",
    supportedBySchool1: "计算机科学学院",
    supportedBySchool2: "医学、牙科与护理学院",
    supportedByInstitute: "新加坡理工学院",
    specialThanksLabel: "特别感谢",
    specialThanksName: "Ms Lim Li Peng",
    specialThanksBody:
      "若没有林丽萍女士的慷慨支持，这个项目绝不可能完成。身为专业瑜伽导师，她为了多次的视频拍摄付出了无数时间——耐心地一次又一次示范每个体式、配合重拍，并分享她的专业知识，确保每个动作都安全易学。她的时间、用心与鼓励，让这个项目从一个构想走到我们如今引以为傲的成果，我们由衷感激。",
    specialThanksLink: "访问林女士的瑜伽工作坊 ↗",
    openByDesign: "开放，是我们的设计理念。",
    openByDesignBody: "为学习、身心健康与公众利益而生。",
    viewOnGithub: "在 GitHub 上查看 ↗",
    repo1Name: "healyoga — 本网页应用",
    repo1Desc:
      "本项目。探索生成式 AI 的实践应用，并采用免账号设计，让用户无需安装、无需注册即可立即开始练习。",
    repo2Name: "healyoga-poc — 移动应用",
    repo2Desc:
      "由学生团队开发的正式版本，完成 CS2101 与 CSC2102「专业软件开发与团队项目」模块的要求。属于全功能部署，具备用户账号设计，用于追踪瑜伽训练进度的混合式移动应用。",
    ...englishTermsUi,

    footerTagline: "轻柔活动身体，自在呼吸，安全练习。",
    footerAttribution: "格拉斯哥大学 · 学术项目",
    footerTerms: "条款与条件",
    termsOnlyNotice: "本页面（条款与条件及使用权声明）仅提供英文版本。",

    languageLabel: "语言",

    disclaimerTitle: "开始之前，请先阅读",
    disclaimerPoint1: "这是一项学生教学项目，仅供教育用途而制作。",
    disclaimerPoint2: "我们已尽力确保内容正确，但无法保证所有信息皆完全无误。",
    disclaimerPoint3: "英文以外的语言版本均由机器翻译生成，可能存在误译之处。",
    disclaimerPoint4: "使用本网站任何内容时，请留意自身安全，并自行承担相关责任。",
    disclaimerRemember: "在本次浏览期间记住我的选择",
    disclaimerAgree: "我同意，继续浏览",
    disclaimerDisagree: "我不同意",
  },
  ms: {
    navPractice: "Latihan",
    navInterviews: "Temu Bual",
    navCredits: "Kredit",
    brandHome: "Laman utama Heal Yoga",

    heroEyebrow: "Pergerakan untuk setiap tubuh",
    heroTitleLine1: "Cari keseimbangan anda,",
    heroTitleLine2: "satu posisi pada satu masa.",
    heroBody: "Demonstrasi yoga yang mudah diikuti dan dipandu jurulatih, direka untuk pelajar, warga emas, dan semua orang yang baru memulakan perjalanan kesihatan mereka.",
    heroCta: "Terokai 22 latihan",

    libraryEyebrow: "Perpustakaan berpandu",
    libraryTitle: "Pilih latihan anda",
    searchPlaceholder: "Cari posisi",
    searchAriaLabel: "Cari posisi yoga",
    filtersAriaLabel: "Tapis mengikut jenis latihan",
    emptyResults: "Tiada posisi yang sepadan dengan carian anda. Cuba kata kunci lain.",

    interviewsEyebrow: "Perbualan tentang kesejahteraan",
    interviewsTitleLine1: "Dengar daripada mereka",
    interviewsTitleLine2: "yang berada di sebalik latihan ini.",
    interviewsBody: "Pandangan ringkas daripada profesional klinikal dan yoga mengenai pergerakan mudah diikuti, penuaan sihat, dan pemikiran di sebalik Heal Yoga.",
    nowPlaying: "Sedang dimainkan",
    playInterview: "Main temu bual",

    writtenPhotoName: "A/Prof Kamala Devi",
    writtenPhotoAffiliation1: "Sekolah Perubatan, Pergigian & Kejururawatan",
    writtenPhotoAffiliation2: "Universiti Glasgow",
    writtenEyebrow: "Dalam kata-katanya sendiri",
    writtenTitle: "Perspektif kejururawatan tentang Heal Yoga",
    writtenP1: "Objektif pelancaran aplikasi ini adalah untuk membantu warga emas membina asas dalam latihan yoga; membantu mereka menjadikan latihan sebagai kebiasaan; membantu mereka mengukuhkan tubuh, menenangkan fikiran dan berasa gembira melalui latihan yang berterusan.",
    writtenP2: "Terdapat pelbagai posisi yoga. Aplikasi ini memaparkan beberapa posisi yang terkenal dan mudah diikuti untuk warga emas, kerana adalah penting bagi warga emas mempelajari posisi yang berguna sambil memastikan posisi tersebut tidak terlalu sukar diikuti.",
    writtenP3: "Istilah “warga emas” digunakan secara longgar di sini: ia boleh bermaksud pesara; mereka yang telah mencapai umur persaraan tetapi masih bekerja; mereka yang belum mencapai umur persaraan tetapi memilih untuk berhenti bekerja lebih awal; atau golongan pekerja yang merasakan mereka kekurangan stamina untuk bersenam tetapi ingin mencuba yoga.",
    writtenP4: "Aplikasi ini mengandungi posisi yoga kerusi untuk pemula, serta posisi peringkat pertengahan dan lanjutan di atas tikar. Oleh kerana aplikasi ini disasarkan kepada warga emas yang berlatih sendiri tanpa bimbingan, posisi yang dipilih dikekalkan mudah dan senang diikuti. Urutan direka supaya warga emas dapat melakukan pemanasan, latihan posisi dan penyejukan badan. Posisi ini bertujuan menyediakan regangan, penguatan otot, latihan kardio, keseimbangan dan latihan pernafasan, serta merangkumi satah sagital, frontal dan transversal supaya latihan meliputi semua arah pergerakan dengan menyeluruh.",
    writtenP5: "Peringatan penting untuk warga emas yang menggunakan aplikasi ini ialah bernafas secara dalam dan tenang semasa berlatih, yang merupakan intipati yoga. Latihan yoga yang berterusan membantu mengukuhkan tubuh, memperbaiki postur, menenangkan fikiran, meningkatkan tumpuan, meningkatkan daya tahan dan menggalakkan kehidupan yang positif.",
    writtenContentHeading: "Kandungan",
    writtenContentChairLabel: "Yoga kerusi (peringkat pemula)",
    writtenContentChairBody: " — Berlatih dengan kerusi membantu warga emas beralih dengan lebih mudah ke posisi yang mereka rasa mencabar dan kekal lebih lama dalam posisi tersebut untuk mendapat manfaatnya. Yoga kerusi amat disyorkan apabila latihan di atas lantai tidak dapat diakses atau tidak praktikal.",
    writtenContentSunLabel: "Sun Salutation (peringkat pertengahan dan lanjutan)",
    writtenContentSunBody: " — Satu urutan pergerakan penting dalam asana yoga yang menggalakkan kesihatan tulang belakang, pembukaan bahu dan dada, serta kekuatan anggota badan dan teras. Ia boleh digunakan sebagai pemanasan setelah warga emas mahir dengan posisi tersebut; peringkat pertengahan menumpukan kepada posisi berasingan manakala peringkat lanjutan menumpukan kepada urutan pergerakan dan latihan kardio.",
    writtenFeaturesHeading: "Ciri-ciri aplikasi",
    writtenFeaturesBody: "Untuk menggalakkan latihan yang berterusan dan kerap, aplikasi ini membantu warga emas menjejaki kemajuan mereka dengan memaparkan jumlah tempoh latihan mingguan mereka. Setelah mencapai satu pencapaian, mereka akan menerima trofi. Kami juga menjejaki perasaan warga emas dengan mengemukakan beberapa soalan selepas sebulan berlatih, bagi meningkatkan kesedaran tubuh mereka.",
    writtenNursingHeading: "Pandangan dari sudut kejururawatan",
    writtenNursingBody: "Latihan yoga yang berterusan menawarkan pelbagai manfaat kesihatan yang amat relevan untuk warga emas. Dari segi fisiologi, yoga meningkatkan kekuatan otot-rangka, mobiliti sendi dan keseimbangan, sekali gus mengurangkan risiko jatuh, satu kebimbangan utama dalam penjagaan geriatrik. Pernafasan terkawal dan pergerakan yang penuh kesedaran meningkatkan daya tahan kardiopulmonari dan membantu pengurusan yang lebih baik terhadap keadaan kronik seperti tekanan darah tinggi, diabetes dan artritis. Dari segi psikologi, yoga menggalakkan relaksasi, mengurangkan kebimbangan, dan meningkatkan daya tahan emosi, yang penting untuk mengekalkan kesejahteraan mental pada usia lanjut. Yang lebih penting, yoga menggalakkan keyakinan diri dan penyertaan aktif dalam penjagaan kesihatan, selaras dengan matlamat kejururawatan untuk memperkasakan individu mengawal kesihatan mereka sendiri dan menggalakkan penjagaan holistik yang berpusatkan insan.",

    creditsEyebrow: "Kerjasama universiti",
    creditsTitleLine1: "Dibina dengan teliti.",
    creditsTitleLine2: "Dikongsi dengan tujuan.",
    creditsBody: "Heal Yoga ialah inisiatif pendidikan tinggi yang menggunakan teknologi mudah alih sumber terbuka untuk menjadikan latihan yoga dan kesedaran kesihatan awam lebih mudah diakses oleh golongan muda dan warga emas.",
    devTeamKicker: "Pasukan pembangunan",
    devTeamCourse: "Pembangunan Perisian Profesional & Projek Berpasukan",
    facultyAdvisorLabel: "Penasihat fakulti",
    facultyAdvisorName: "Dr Peter CY Yau",
    facultyAdvisorGithub: "github.com/drpeteryau ↗",
    supportedByLabel: "Disokong oleh",
    supportedByUniversity: "Universiti Glasgow",
    supportedBySchool1: "Sekolah Sains Komputer",
    supportedBySchool2: "Sekolah Perubatan, Pergigian & Kejururawatan",
    supportedByInstitute: "Institut Teknologi Singapura",
    specialThanksLabel: "Penghargaan khas",
    specialThanksName: "Ms Lim Li Peng",
    specialThanksBody:
      "Projek ini tidak mungkin dapat disiapkan tanpa sokongan murah hati Ms Lim Li Peng. Sebagai jurulatih yoga profesional kami, beliau meluangkan begitu banyak masa untuk pelbagai pusingan rakaman video — dengan sabar menunjukkan dan menunjukkan semula setiap posisi, membimbing penggambaran semula, serta berkongsi kepakaran beliau supaya setiap pergerakan selamat dan mudah diikuti. Masa, keprihatinan, dan galakan beliau telah membawa projek ini daripada satu idea kepada sesuatu yang benar-benar kami banggakan, dan kami amat menghargainya.",
    specialThanksLink: "Lawati bengkel yoga Ms Lim ↗",
    openByDesign: "Terbuka mengikut reka bentuk.",
    openByDesignBody: "Dicipta untuk pembelajaran, kesejahteraan, dan manfaat awam.",
    viewOnGithub: "Lihat di GitHub ↗",
    repo1Name: "healyoga — aplikasi web ini",
    repo1Desc:
      "Projek ini. Meneroka penggunaan praktikal Gen AI dan reka bentuk aplikasi web tanpa akaun, supaya sesiapa sahaja boleh mula berlatih serta-merta tanpa pemasangan dan tanpa pendaftaran.",
    repo2Name: "healyoga-poc — aplikasi mudah alih",
    repo2Desc:
      "Pengeluaran oleh pasukan pelajar, memenuhi keperluan modul CS2101 & CSC2102 Pembangunan Perisian Profesional dan Projek Pasukan. Penggunaan berfungsi penuh dengan reka bentuk akaun pengguna, untuk aplikasi hibrid mudah alih latihan yoga yang menjejak kemajuan.",
    ...englishTermsUi,

    footerTagline: "Bergerak dengan lembut. Bernafas dengan bebas. Berlatih dengan selamat.",
    footerAttribution: "Universiti Glasgow · Projek Akademik",
    footerTerms: "Terma & Syarat",
    termsOnlyNotice: "Halaman ini (Terma & Syarat serta Notis Pelesenan) hanya tersedia dalam bahasa Inggeris.",

    languageLabel: "Bahasa",

    disclaimerTitle: "Sebelum anda bermula",
    disclaimerPoint1: "Ini adalah projek pembelajaran dan pengajaran pelajar, dicipta untuk tujuan pendidikan.",
    disclaimerPoint2: "Kami berusaha sedaya upaya untuk memastikan kandungan ini tepat, tetapi kami tidak dapat menjamin semua maklumat adalah betul.",
    disclaimerPoint3: "Bahasa selain bahasa Inggeris diterjemahkan secara automatik oleh mesin dan mungkin mengandungi kesilapan.",
    disclaimerPoint4: "Sila ambil perhatian terhadap keselamatan diri anda, dan anda bertanggungjawab ke atas diri sendiri semasa mengikuti mana-mana kandungan di laman web ini.",
    disclaimerRemember: "Ingat pilihan saya untuk sesi ini",
    disclaimerAgree: "Saya Setuju, Teruskan",
    disclaimerDisagree: "Saya Tidak Setuju",
  },
  ta: {
    navPractice: "பயிற்சி",
    navInterviews: "நேர்காணல்கள்",
    navCredits: "பங்களிப்பாளர்கள்",
    brandHome: "Heal Yoga முகப்புக்குச் செல்ல",

    heroEyebrow: "ஒவ்வொரு உடலுக்கும் ஏற்ற இயக்கம்",
    heroTitleLine1: "உங்கள் சமநிலையைக் கண்டறியுங்கள்,",
    heroTitleLine2: "ஒரு தோரணையில் இருந்து மற்றொன்றுக்கு.",
    heroBody: "மாணவர்கள், முதியோர், மற்றும் நலவாழ்வுப் பயணத்தைத் தொடங்கும் அனைவருக்காகவும் வடிவமைக்கப்பட்ட, பயிற்சியாளர் வழிகாட்டும் எளிய யோகா நிரூபணங்கள்.",
    heroCta: "22 பயிற்சிகளை ஆராயுங்கள்",

    libraryEyebrow: "வழிகாட்டப்பட்ட நூலகம்",
    libraryTitle: "உங்கள் பயிற்சியைத் தேர்ந்தெடுங்கள்",
    searchPlaceholder: "தோரணைகளைத் தேடுங்கள்",
    searchAriaLabel: "யோகா தோரணைகளைத் தேடுங்கள்",
    filtersAriaLabel: "பயிற்சி வகையின்படி வடிகட்டுங்கள்",
    emptyResults: "உங்கள் தேடலுக்குப் பொருந்தும் தோரணைகள் இல்லை. வேறு சொல்லை முயற்சிக்கவும்.",

    interviewsEyebrow: "நலவாழ்வு குறித்த உரையாடல்கள்",
    interviewsTitleLine1: "பயிற்சிக்குப் பின்னால் உள்ளவர்களின்",
    interviewsTitleLine2: "கருத்துகளைக் கேளுங்கள்.",
    interviewsBody: "அணுகக்கூடிய இயக்கம், ஆரோக்கியமான முதுமை, மற்றும் Heal Yoga-வுக்குப் பின்னணியிலுள்ள சிந்தனை குறித்து மருத்துவ மற்றும் யோகா நிபுணர்களின் சுருக்கமான கருத்துகள்.",
    nowPlaying: "இப்போது ஒளிபரப்பப்படுகிறது",
    playInterview: "நேர்காணலை இயக்கு",

    writtenPhotoName: "A/Prof Kamala Devi",
    writtenPhotoAffiliation1: "மருத்துவம், பல் மருத்துவம் மற்றும் நர்சிங் பள்ளி",
    writtenPhotoAffiliation2: "கிளாஸ்கோ பல்கலைக்கழகம்",
    writtenEyebrow: "அவரது சொந்த வார்த்தைகளில்",
    writtenTitle: "Heal Yoga குறித்த ஒரு நர்சிங் பார்வை",
    writtenP1: "இந்த செயலியைத் தொடங்குவதன் நோக்கங்கள், முதியோர் யோகா பயிற்சியில் ஒரு அடித்தளத்தை உருவாக்க உதவுவது; அவர்களது பயிற்சியை ஒரு பழக்கமாக மாற்ற உதவுவது; தொடர்ச்சியான பயிற்சியின் மூலம் அவர்களது உடலை வலுப்படுத்தவும், மனதை அமைதிப்படுத்தவும், மகிழ்ச்சியை உணரவும் உதவுவது ஆகும்.",
    writtenP2: "யோகா தோரணைகள் ஏராளம் உள்ளன. முதியோருக்குப் பயனுள்ள தோரணைகளைக் கற்றுக்கொள்வது மிக முக்கியம் என்பதால், அவற்றை மிகவும் கடினமாக இல்லாமல் பின்பற்றக்கூடியதாக வைத்திருக்கும் வகையில், நன்கு அறியப்பட்ட மற்றும் எளிதில் அணுகக்கூடிய சில தோரணைகளை இந்த செயலி சிறப்பித்துக் காட்டுகிறது.",
    writtenP3: "இங்கு “முதியோர்” என்ற சொல் தளர்வாகப் பயன்படுத்தப்படுகிறது: இது ஓய்வூதியம் பெற்றவர்களையும்; ஓய்வு வயதை எட்டியும் இன்னும் வேலை செய்பவர்களையும்; ஓய்வு வயதை எட்டாமலேயே பணியிலிருந்து விலக விரும்புபவர்களையும்; அல்லது உடற்பயிற்சி செய்ய தமக்குப் போதிய சக்தி இல்லை எனக் கருதி, ஆனால் யோகாவை முயற்சிக்க விரும்பும் பணிபுரியும் பெரியவர்களையும் குறிக்கலாம்.",
    writtenP4: "இந்த செயலியில் ஆரம்பநிலையாளர்களுக்கான நாற்காலி யோகா தோரணைகளும், பாயின் மீது செய்யப்படும் இடைநிலை மற்றும் மேம்பட்ட நிலை தோரணைகளும் உள்ளன. வழிகாட்டுதல் இன்றி தாமே பயிற்சி செய்யும் முதியோருக்காக இந்த செயலி வடிவமைக்கப்பட்டிருப்பதால், தோரணைகள் எளிமையாகவும் அணுகக்கூடியதாகவும் வைக்கப்பட்டுள்ளன. முதியோர் உடல் சூடேற்றம், தோரணைப் பயிற்சி, மற்றும் உடலை அமைதிப்படுத்தும் முறையில் வரிசை வடிவமைக்கப்பட்டுள்ளது. இந்த தோரணைகள் நீட்சி, தசை வலுப்படுத்துதல், இதய-நுரையீரல் பயிற்சி, சமநிலை மற்றும் மூச்சுப் பயிற்சி ஆகியவற்றை வழங்கும் நோக்கத்துடன், sagittal, frontal மற்றும் transverse எனும் மூன்று இயக்கத் தளங்களையும் உள்ளடக்கி, பயிற்சி அனைத்துத் திசைகளிலும் முழுமையாக இருக்குமாறு வடிவமைக்கப்பட்டுள்ளன.",
    writtenP5: "இந்த செயலியைப் பயன்படுத்தும் முதியோருக்கான ஒரு முக்கியமான நினைவூட்டல், பயிற்சியின் போது ஆழமாகவும் அமைதியாகவும் மூச்சு விடுவதே ஆகும், இதுவே யோகாவின் சாரம். தொடர்ச்சியான யோகா பயிற்சி உடலை வலுப்படுத்தவும், தோற்றத்தை சீரமைக்கவும், மனதை அமைதிப்படுத்தவும், கவனத்தை மேம்படுத்தவும், சகிப்புத்தன்மையை அதிகரிக்கவும், நேர்மறையான வாழ்க்கையை ஊக்குவிக்கவும் உதவுகிறது.",
    writtenContentHeading: "உள்ளடக்கம்",
    writtenContentChairLabel: "நாற்காலி யோகா (ஆரம்ப நிலை)",
    writtenContentChairBody: " — நாற்காலியுடன் பயிற்சி செய்வது, முதியோர் தமக்குச் சவாலாக இருக்கும் தோரணைகளுக்குள் எளிதாக நுழையவும், அதன் பலனைப் பெற தோரணையில் நீண்ட நேரம் தங்கவும் உதவுகிறது. தரையில் பயிற்சி செய்ய இயலாத அல்லது நடைமுறைக்குப் பொருந்தாத சூழலில் நாற்காலி யோகா மிகவும் பரிந்துரைக்கப்படுகிறது.",
    writtenContentSunLabel: "சூரிய நமஸ்காரம் (இடைநிலை மற்றும் மேம்பட்ட நிலை)",
    writtenContentSunBody: " — முதுகெலும்பு ஆரோக்கியத்தை, தோள்பட்டை மற்றும் மார்பு விரிவாக்கத்தை, மற்றும் கை கால் மற்றும் மைய பலத்தை ஊக்குவிக்கும் யோகா ஆசனங்களின் முக்கியமான ஓட்ட வரிசை இதுவாகும். முதியோர் தோரணைகளுடன் பழக்கமான பின்னர் இதனை உடல் சூடேற்றமாகப் பயன்படுத்தலாம்; இடைநிலை நிலை தனித்தனி தோரணைகளில் கவனம் செலுத்துகிறது, மேம்பட்ட நிலை ஓட்ட வரிசை மற்றும் இதய பயிற்சியில் கவனம் செலுத்துகிறது.",
    writtenFeaturesHeading: "செயலியின் அம்சங்கள்",
    writtenFeaturesBody: "தொடர்ச்சியான, அடிக்கடி நடைபெறும் பயிற்சியை ஊக்குவிக்க, முதியோரது வாராந்திர மொத்த பயிற்சி காலத்தைக் காட்டி, அவர்களது முன்னேற்றத்தைக் கண்காணிக்க இந்த செயலி உதவுகிறது. ஒரு மைல்கல் எட்டப்படும்போது, அவர்களுக்கு ஒரு கோப்பை வழங்கப்படுகிறது. ஒரு மாத பயிற்சிக்குப் பின், முதியோரின் உடல் விழிப்புணர்வை அதிகரிக்க, சில கேள்விகளைக் கேட்பதன் மூலம் அவர்கள் எவ்வாறு உணர்கிறார்கள் என்பதையும் நாங்கள் கண்காணிக்கிறோம்.",
    writtenNursingHeading: "நர்சிங் பார்வையில்",
    writtenNursingBody: "தொடர்ச்சியான யோகா பயிற்சி, குறிப்பாக முதியோருக்குப் பொருந்தக்கூடிய பன்முக ஆரோக்கிய நன்மைகளை வழங்குகிறது. உடலியல் அடிப்படையில், யோகா தசை-எலும்பு வலிமையையும், மூட்டு இயக்கத்தையும், சமநிலையையும் மேம்படுத்துகிறது, இதனால் முதியோர் பராமரிப்பில் முக்கிய கவலையாக இருக்கும் விழும் அபாயத்தைக் குறைக்கிறது. கட்டுப்படுத்தப்பட்ட மூச்சு மற்றும் கவனத்துடன் கூடிய இயக்கம் இதய-நுரையீரல் சகிப்புத்தன்மையை மேம்படுத்தி, உயர் இரத்த அழுத்தம், நீரிழிவு, மூட்டுவாதம் போன்ற நீண்டகால நோய்களை சிறப்பாக நிர்வகிக்க உதவுகிறது. உளவியல் அடிப்படையில், யோகா தளர்வை ஊக்குவித்து, பதற்றத்தைக் குறைத்து, உணர்ச்சி நெகிழ்ச்சித்தன்மையை மேம்படுத்துகிறது, இது முதுமையில் மனநலத்தை பேணுவதற்கு இன்றியமையாதது. மேலும் முக்கியமாக, யோகா தன்னம்பிக்கையை ஊக்குவித்து, ஆரோக்கிய பராமரிப்பில் தீவிர பங்களிப்பை ஊக்குவிக்கிறது, இது தனிநபர்கள் தமது சொந்த ஆரோக்கியத்தைக் கட்டுப்படுத்த அதிகாரம் அளிக்கும் மற்றும் முழுமையான, மனிதநேய மைய பராமரிப்பை ஊக்குவிக்கும் நர்சிங் இலக்குகளுடன் ஒத்துப்போகிறது.",

    creditsEyebrow: "ஒரு பல்கலைக்கழக கூட்டிணைவு",
    creditsTitleLine1: "அக்கறையுடன் உருவாக்கப்பட்டது.",
    creditsTitleLine2: "நோக்கத்துடன் பகிரப்பட்டது.",
    creditsBody: "Heal Yoga என்பது திறந்த மூல மொபைல் தொழில்நுட்பத்தைப் பயன்படுத்தி, யோகா பயிற்சியையும் பொது சுகாதார விழிப்புணர்வையும் இளையோருக்கும் முதியோருக்கும் மேலும் அணுகக்கூடியதாக்கும் ஒரு உயர்கல்வித் திட்டமாகும்.",
    devTeamKicker: "மேம்பாட்டுக் குழு",
    devTeamCourse: "தொழில்முறை மென்பொருள் மேம்பாடு & குழு திட்டம்",
    facultyAdvisorLabel: "பீடம் ஆலோசகர்",
    facultyAdvisorName: "Dr Peter CY Yau",
    facultyAdvisorGithub: "github.com/drpeteryau ↗",
    supportedByLabel: "ஆதரவளிப்பவர்",
    supportedByUniversity: "கிளாஸ்கோ பல்கலைக்கழகம்",
    supportedBySchool1: "கணினியியல் பள்ளி",
    supportedBySchool2: "மருத்துவம், பல் மருத்துவம் மற்றும் நர்சிங் பள்ளி",
    supportedByInstitute: "சிங்கப்பூர் தொழில்நுட்ப நிறுவனம்",
    specialThanksLabel: "சிறப்பு நன்றி",
    specialThanksName: "Ms Lim Li Peng",
    specialThanksBody:
      "Ms Lim Li Peng அவர்களின் தாராளமான ஆதரவில்லாமல் இந்தத் திட்டம் உருவாக முடியாது. எங்கள் தொழில்முறை யோகா பயிற்சியாளராக, பல கட்ட வீடியோ படப்பிடிப்புகளுக்காக அவர் எண்ணற்ற நேரத்தை ஒதுக்கினார் — ஒவ்வொரு தோரணையையும் பொறுமையாக மீண்டும் மீண்டும் காட்டி, மறுபதிவுகளை வழிநடத்தி, ஒவ்வொரு இயக்கமும் பாதுகாப்பாகவும் எளிதாகவும் பின்பற்றக்கூடியதாக இருக்க தனது நிபுணத்துவத்தைப் பகிர்ந்தார். அவரது நேரம், அக்கறை, மற்றும் ஊக்கமே இந்தத் திட்டத்தை ஒரு எண்ணத்திலிருந்து நாங்கள் பெருமைப்படும் ஒன்றாக மாற்றியது; அதற்கு நாங்கள் ஆழ்ந்த நன்றியுடையோம்.",
    specialThanksLink: "Ms Lim அவர்களின் யோகா பயிற்சி நிலையத்தைப் பார்வையிடுங்கள் ↗",
    openByDesign: "திறந்த தன்மையே எங்கள் வடிவமைப்பு நோக்கம்.",
    openByDesignBody: "கற்றல், நலவாழ்வு, மற்றும் பொது நலனுக்காக உருவாக்கப்பட்டது.",
    viewOnGithub: "GitHub-இல் பார்க்க ↗",
    repo1Name: "healyoga — இந்த வலை பயன்பாடு",
    repo1Desc:
      "இந்தத் திட்டம். நடைமுறை Gen AI பயன்பாடுகளையும், நிறுவல் இல்லாமல், பதிவு இல்லாமல் உடனடியாகப் பயிற்சியைத் தொடங்கக்கூடிய கணக்கு-இல்லா வலை பயன்பாட்டு வடிவமைப்பையும் ஆராய்கிறது.",
    repo2Name: "healyoga-poc — மொபைல் பயன்பாடு",
    repo2Desc:
      "CS2101 & CSC2102 தொழில்முறை மென்பொருள் மேம்பாடு மற்றும் குழு திட்ட தொகுதிகளின் தேவைகளை நிறைவேற்றும் வகையில் மாணவர் குழுவால் தயாரிக்கப்பட்ட முழுமையான வெளியீடு. முன்னேற்றத்தைக் கண்காணிக்கும் யோகா பயிற்சிக்கான முழு செயல்பாட்டு மொபைல் ஹைபிரிட் பயன்பாட்டிற்கு, பயனர் கணக்கு வடிவமைப்புடன் கூடிய முழுமையான வரிசைப்படுத்தல்.",
    ...englishTermsUi,

    footerTagline: "மென்மையாக இயங்குங்கள். சுதந்திரமாக மூச்சு விடுங்கள். பாதுகாப்பாக பயிற்சி செய்யுங்கள்.",
    footerAttribution: "கிளாஸ்கோ பல்கலைக்கழகம் · கல்விசார் திட்டம்",
    footerTerms: "விதிமுறைகள் & நிபந்தனைகள்",
    termsOnlyNotice: "இந்தப் பக்கம் (விதிமுறைகள் & நிபந்தனைகள் மற்றும் உரிம அறிவிப்பு) ஆங்கிலத்தில் மட்டுமே கிடைக்கும்.",

    languageLabel: "மொழி",

    disclaimerTitle: "தொடங்குவதற்கு முன்",
    disclaimerPoint1: "இது கல்வி நோக்கங்களுக்காக உருவாக்கப்பட்ட ஒரு மாணவர் கற்றல் மற்றும் கற்பித்தல் திட்டமாகும்.",
    disclaimerPoint2: "உள்ளடக்கத்தை துல்லியமாக வைத்திருக்க நாங்கள் எங்களால் இயன்றவரை முயற்சிக்கிறோம், ஆனால் அனைத்து தகவல்களும் சரியானவை என்பதை உறுதிசெய்ய முடியாது.",
    disclaimerPoint3: "ஆங்கிலம் தவிர்த்த மொழிகள் இயந்திர மொழிபெயர்ப்பால் தரப்பட்டவை, அவற்றில் பிழைகள் இருக்கக்கூடும்.",
    disclaimerPoint4: "இந்த தளத்தில் உள்ள எந்தவொரு உள்ளடக்கத்தையும் பின்பற்றும்போது உங்கள் சொந்த பாதுகாப்பில் கவனமாக இருங்கள்; நீங்களே அதற்குப் பொறுப்பு.",
    disclaimerRemember: "இந்த அமர்வுக்கு எனது தேர்வை நினைவில் வையுங்கள்",
    disclaimerAgree: "நான் ஒப்புக்கொள்கிறேன், தொடரவும்",
    disclaimerDisagree: "நான் ஒப்புக்கொள்ளவில்லை",
  },
};

export const categoryLabels: Record<Locale, Record<Category | "All", string>> = {
  en: {
    All: "All",
    Advanced: "Advanced",
    Intermediate: "Intermediate",
    Standing: "Standing",
    Sitting: "Sitting",
    Interview: "Interview",
  },
  "zh-Hant": {
    All: "全部",
    Advanced: "進階",
    Intermediate: "中階",
    Standing: "站姿",
    Sitting: "坐姿",
    Interview: "訪談",
  },
  "zh-Hans": {
    All: "全部",
    Advanced: "进阶",
    Intermediate: "中阶",
    Standing: "站姿",
    Sitting: "坐姿",
    Interview: "访谈",
  },
  ms: {
    All: "Semua",
    Advanced: "Lanjutan",
    Intermediate: "Pertengahan",
    Standing: "Berdiri",
    Sitting: "Duduk",
    Interview: "Temu Bual",
  },
  ta: {
    All: "அனைத்தும்",
    Advanced: "மேம்பட்ட நிலை",
    Intermediate: "இடைநிலை",
    Standing: "நின்று செய்யும்",
    Sitting: "அமர்ந்து செய்யும்",
    Interview: "நேர்காணல்",
  },
};

type VideoText = { title: string; description?: string; question?: string };

export const videoText: Record<Locale, Record<string, VideoText>> = {
  en: {
    egNdbDDS_Ws: { title: "Interview 01 — A/Prof CK Seow", question: "Why does Glasgow Computing Science support an open-source yoga mobile app project?" },
    dyYVJnccUx0: { title: "Interview 02 — A/Prof CK Seow", question: "What value does this project bring to students and industry partners?" },
    IsGAZrjEMp4: { title: "Interview 03 — Ms LP Lim", question: "How often should elderly and youth practice yoga for best results?" },
    jV6KZ2no0Pg: { title: "Interview 02 — Ms LP Lim", question: "Is yoga safe for elderly people and beginners?" },
    CiJ0R9ZugeY: { title: "Interview 01 — Ms LP Lim", question: "What are the key benefits of yoga for elderly and youth?" },
    mzqsdpvfDto: {
      title: "Sun Salutation Flow",
      description: "A dynamic sequence that links breath with movement, warming up the whole body while improving flexibility, mobility, and circulation.",
    },
    m0b_BebYNBQ: {
      title: "Baby Cobra",
      description: "A gentle backbend that opens the chest and strengthens the upper back while encouraging mobility through the spine.",
    },
    hComtEvbgN4: {
      title: "Eight-Point Pose",
      description: "A controlled lowering position where eight points of the body connect with the floor, helping strengthen the arms, shoulders, chest, and core.",
    },
    "Ma93Zxwp_-o": {
      title: "Plank",
      description: "A full body strength pose that engages the core, shoulders, arms, and legs while building stability and body control.",
    },
    "0MUxqZmmmq8": {
      title: "Downward Dog",
      description: "A full body stretch that lengthens the spine, shoulders, hamstrings, and calves while strengthening the upper body.",
    },
    ze9cJVnkYOg: {
      title: "Triangle Pose",
      description: "A standing stretch that opens the hips and chest while lengthening the sides of the body and improving balance.",
    },
    "aP40k--wiPo": {
      title: "Side Angle Pose",
      description: "A deep standing stretch that strengthens the legs while opening the hips, chest, shoulders, and side body.",
    },
    "1EmtCVdAKuI": {
      title: "Reverse Warrior 2",
      description: "A flowing side stretch from Warrior 2 that opens the ribs and waist while maintaining strength and stability through the legs.",
    },
    D8OEOqj6LKo: {
      title: "Warrior 2",
      description: "A strong standing pose that builds leg endurance and hip mobility while opening the chest and improving balance.",
    },
    ETFrnz9CCsw: {
      title: "Warrior 1",
      description: "A powerful standing pose that strengthens the legs while stretching the hips and opening the chest and shoulders.",
    },
    vpECbuWGnVw: {
      title: "Warrior 3",
      description: "A single leg balance that challenges stability while strengthening the legs, core, back, and glutes.",
    },
    "zr-EsTGQE3g": {
      title: "Standing Crunch",
      description: "A standing core movement that brings the upper and lower body together, activating the abdominal muscles while improving coordination and balance.",
    },
    qJHd5KIO35I: {
      title: "Back and Chest Stretch",
      description: "A mobility stretch that opens the chest and shoulders while releasing tension through the upper back.",
    },
    Z_LIRhABH7c: {
      title: "Goddess Pose (Leg Stretch)",
      description: "A wide stance squat that opens the hips and inner thighs while strengthening the glutes, thighs, and legs.",
    },
    r4ixF0BmzfI: {
      title: "Goddess Pose (Shoulders and Torso Twist)",
      description: "A Goddess stance combined with an upper body rotation to stretch the shoulders and spine while maintaining lower body strength.",
    },
    "78t9qqSWf4Q": {
      title: "Leg Raise (Straight)",
      description: "A controlled straight leg lift that strengthens the hip flexors and core while helping improve lower body mobility.",
    },
    "6tlBgzidSuU": {
      title: "Leg Raise (Bent)",
      description: "A bent knee leg lift that activates the core and hip muscles with a more controlled and accessible range of motion.",
    },
    "vkb-jrEq4sc": {
      title: "Shoulders and Torso Twist",
      description: "A rotational stretch that mobilizes the spine while releasing tension through the shoulders, chest, and upper back.",
    },
    "5jSzGqTOTeY": {
      title: "Shoulders Lateral Stretch",
      description: "A side bending stretch that lengthens the shoulders, upper back, waist, and sides of the torso.",
    },
    "-K7puFfQgIc": {
      title: "Bent Arm Rotation",
      description: "A shoulder mobility movement using bent arms to gently rotate the shoulder joints and loosen the upper body.",
    },
    oCGcR5GgpWI: {
      title: "Straight Arms Rotation",
      description: "A controlled arm rotation that works through a larger shoulder range of motion to improve mobility and warm up the shoulders.",
    },
    ZhelQy85j3M: {
      title: "Head, Neck and Shoulders Stretch",
      description: "A gentle mobility sequence designed to release tension around the neck, shoulders, and upper back while improving comfortable range of motion.",
    },
  },
  "zh-Hant": {
    egNdbDDS_Ws: { title: "訪談 01 — A/Prof CK Seow", question: "格拉斯哥大學計算機科學系為何支持這項開源瑜伽手機應用程式專案？" },
    dyYVJnccUx0: { title: "訪談 02 — A/Prof CK Seow", question: "這項專案為學生與業界夥伴帶來什麼價值？" },
    IsGAZrjEMp4: { title: "訪談 03 — Ms LP Lim", question: "長者與年輕人多久練習一次瑜伽效果最好？" },
    jV6KZ2no0Pg: { title: "訪談 02 — Ms LP Lim", question: "瑜伽對長者與初學者是否安全？" },
    CiJ0R9ZugeY: { title: "訪談 01 — Ms LP Lim", question: "瑜伽對長者與年輕人有哪些主要益處？" },
    mzqsdpvfDto: {
      title: "拜日式流",
      description: "一套結合呼吸與動作的連貫序列，能喚醒全身、提升柔軟度、關節活動度與血液循環。",
    },
    m0b_BebYNBQ: {
      title: "嬰兒眼鏡蛇式",
      description: "溫和的後彎體式，能打開胸腔、強化上背肌力，同時促進脊椎的活動度。",
    },
    hComtEvbgN4: {
      title: "八點式",
      description: "身體以八個支點緩緩下降貼地的控制性動作，有助強化手臂、肩膀、胸部與核心肌群。",
    },
    "Ma93Zxwp_-o": {
      title: "棒式",
      description: "全身性的力量體式，同時運用核心、肩膀、手臂與雙腿，建立穩定度與身體控制能力。",
    },
    "0MUxqZmmmq8": {
      title: "下犬式",
      description: "全身性的伸展體式，能拉長脊椎、肩膀、大腿後側與小腿，同時強化上半身力量。",
    },
    ze9cJVnkYOg: {
      title: "三角式",
      description: "站姿伸展體式，能打開髖部與胸腔，同時拉長身體側面並改善平衡感。",
    },
    "aP40k--wiPo": {
      title: "側角式",
      description: "深層的站姿伸展體式，能強化雙腿肌力，同時打開髖部、胸部、肩膀與身體側面。",
    },
    "1EmtCVdAKuI": {
      title: "反轉戰士二式",
      description: "由戰士二式延伸而出的流動側身伸展，能打開肋骨與腰側，同時維持雙腿的力量與穩定度。",
    },
    D8OEOqj6LKo: {
      title: "戰士二式",
      description: "強而有力的站姿體式，能增強雙腿耐力與髖部活動度，同時打開胸腔並改善平衡感。",
    },
    ETFrnz9CCsw: {
      title: "戰士一式",
      description: "強而有力的站姿體式，能強化雙腿肌力，同時伸展髖部並打開胸腔與肩膀。",
    },
    vpECbuWGnVw: {
      title: "戰士三式",
      description: "單腳平衡體式，考驗身體穩定度，同時強化雙腿、核心、背部與臀部肌群。",
    },
    "zr-EsTGQE3g": {
      title: "站姿捲腹",
      description: "站立進行的核心動作，將上下半身連結在一起，啟動腹部肌群，同時提升協調性與平衡感。",
    },
    qJHd5KIO35I: {
      title: "背胸伸展",
      description: "提升活動度的伸展體式，能打開胸腔與肩膀，同時釋放上背部的緊繃感。",
    },
    Z_LIRhABH7c: {
      title: "女神式（腿部伸展）",
      description: "寬站姿深蹲體式，能打開髖部與大腿內側，同時強化臀部、大腿與雙腿肌力。",
    },
    r4ixF0BmzfI: {
      title: "女神式（肩部與軀幹扭轉）",
      description: "結合女神式站姿與上半身旋轉動作，伸展肩膀與脊椎，同時維持下半身的力量。",
    },
    "78t9qqSWf4Q": {
      title: "直腿抬升",
      description: "控制性的直腿抬升動作，能強化髖屈肌與核心，同時協助改善下半身活動度。",
    },
    "6tlBgzidSuU": {
      title: "屈膝抬腿",
      description: "屈膝進行的抬腿動作，能啟動核心與髖部肌群，動作範圍更可控、也更容易上手。",
    },
    "vkb-jrEq4sc": {
      title: "肩部與軀幹扭轉",
      description: "旋轉伸展動作，能活動脊椎，同時釋放肩膀、胸部與上背部的緊繃感。",
    },
    "5jSzGqTOTeY": {
      title: "肩部側向伸展",
      description: "側彎伸展體式，能拉長肩膀、上背部、腰部與軀幹側面。",
    },
    "-K7puFfQgIc": {
      title: "屈臂旋轉",
      description: "以屈臂方式進行的肩部活動動作，能輕柔轉動肩關節並放鬆上半身。",
    },
    oCGcR5GgpWI: {
      title: "直臂旋轉",
      description: "控制性的手臂旋轉動作，透過更大範圍的肩部活動，提升活動度並為肩膀暖身。",
    },
    ZhelQy85j3M: {
      title: "頭頸肩伸展",
      description: "溫和的活動序列，能釋放頸部、肩膀與上背部的緊繃感，同時改善舒適的活動範圍。",
    },
  },
  "zh-Hans": {
    egNdbDDS_Ws: { title: "访谈 01 — A/Prof CK Seow", question: "格拉斯哥大学计算机科学系为何支持这项开源瑜伽手机应用程序项目？" },
    dyYVJnccUx0: { title: "访谈 02 — A/Prof CK Seow", question: "这项项目为学生与业界伙伴带来什么价值？" },
    IsGAZrjEMp4: { title: "访谈 03 — Ms LP Lim", question: "长者与年轻人多久练习一次瑜伽效果最好？" },
    jV6KZ2no0Pg: { title: "访谈 02 — Ms LP Lim", question: "瑜伽对长者与初学者是否安全？" },
    CiJ0R9ZugeY: { title: "访谈 01 — Ms LP Lim", question: "瑜伽对长者与年轻人有哪些主要益处？" },
    mzqsdpvfDto: {
      title: "拜日式流",
      description: "一套结合呼吸与动作的连贯序列，能唤醒全身、提升柔软度、关节活动度与血液循环。",
    },
    m0b_BebYNBQ: {
      title: "婴儿眼镜蛇式",
      description: "温和的后弯体式，能打开胸腔、强化上背肌力，同时促进脊椎的活动度。",
    },
    hComtEvbgN4: {
      title: "八点式",
      description: "身体以八个支点缓缓下降贴地的控制性动作，有助强化手臂、肩膀、胸部与核心肌群。",
    },
    "Ma93Zxwp_-o": {
      title: "平板支撑式",
      description: "全身性的力量体式，同时运用核心、肩膀、手臂与双腿，建立稳定度与身体控制能力。",
    },
    "0MUxqZmmmq8": {
      title: "下犬式",
      description: "全身性的伸展体式，能拉长脊椎、肩膀、大腿后侧与小腿，同时强化上半身力量。",
    },
    ze9cJVnkYOg: {
      title: "三角式",
      description: "站姿伸展体式，能打开髋部与胸腔，同时拉长身体侧面并改善平衡感。",
    },
    "aP40k--wiPo": {
      title: "侧角式",
      description: "深层的站姿伸展体式，能强化双腿肌力，同时打开髋部、胸部、肩膀与身体侧面。",
    },
    "1EmtCVdAKuI": {
      title: "反转战士二式",
      description: "由战士二式延伸而出的流动侧身伸展，能打开肋骨与腰侧，同时维持双腿的力量与稳定度。",
    },
    D8OEOqj6LKo: {
      title: "战士二式",
      description: "强而有力的站姿体式，能增强双腿耐力与髋部活动度，同时打开胸腔并改善平衡感。",
    },
    ETFrnz9CCsw: {
      title: "战士一式",
      description: "强而有力的站姿体式，能强化双腿肌力，同时伸展髋部并打开胸腔与肩膀。",
    },
    vpECbuWGnVw: {
      title: "战士三式",
      description: "单脚平衡体式，考验身体稳定度，同时强化双腿、核心、背部与臀部肌群。",
    },
    "zr-EsTGQE3g": {
      title: "站姿卷腹",
      description: "站立进行的核心动作，将上下半身连结在一起，启动腹部肌群，同时提升协调性与平衡感。",
    },
    qJHd5KIO35I: {
      title: "背胸伸展",
      description: "提升活动度的伸展体式，能打开胸腔与肩膀，同时释放上背部的紧绷感。",
    },
    Z_LIRhABH7c: {
      title: "女神式（腿部伸展）",
      description: "宽站姿深蹲体式，能打开髋部与大腿内侧，同时强化臀部、大腿与双腿肌力。",
    },
    r4ixF0BmzfI: {
      title: "女神式（肩部与躯干扭转）",
      description: "结合女神式站姿与上半身旋转动作，伸展肩膀与脊椎，同时维持下半身的力量。",
    },
    "78t9qqSWf4Q": {
      title: "直腿抬升",
      description: "控制性的直腿抬升动作，能强化髋屈肌与核心，同时协助改善下半身活动度。",
    },
    "6tlBgzidSuU": {
      title: "屈膝抬腿",
      description: "屈膝进行的抬腿动作，能启动核心与髋部肌群，动作范围更可控、也更容易上手。",
    },
    "vkb-jrEq4sc": {
      title: "肩部与躯干扭转",
      description: "旋转伸展动作，能活动脊椎，同时释放肩膀、胸部与上背部的紧绷感。",
    },
    "5jSzGqTOTeY": {
      title: "肩部侧向伸展",
      description: "侧弯伸展体式，能拉长肩膀、上背部、腰部与躯干侧面。",
    },
    "-K7puFfQgIc": {
      title: "屈臂旋转",
      description: "以屈臂方式进行的肩部活动动作，能轻柔转动肩关节并放松上半身。",
    },
    oCGcR5GgpWI: {
      title: "直臂旋转",
      description: "控制性的手臂旋转动作，通过更大范围的肩部活动，提升活动度并为肩膀热身。",
    },
    ZhelQy85j3M: {
      title: "头颈肩伸展",
      description: "温和的活动序列，能释放颈部、肩膀与上背部的紧绷感，同时改善舒适的活动范围。",
    },
  },
  ms: {
    egNdbDDS_Ws: { title: "Temu Bual 01 — A/Prof CK Seow" },
    dyYVJnccUx0: { title: "Temu Bual 02 — A/Prof CK Seow" },
    IsGAZrjEMp4: { title: "Temu Bual 03 — Ms LP Lim" },
    jV6KZ2no0Pg: { title: "Temu Bual 02 — Ms LP Lim" },
    CiJ0R9ZugeY: { title: "Temu Bual 01 — Ms LP Lim" },
    mzqsdpvfDto: {
      title: "Aliran Sun Salutation",
      description: "Satu urutan dinamik yang menghubungkan pernafasan dengan pergerakan, memanaskan seluruh badan sambil meningkatkan kelenturan, mobiliti, dan peredaran darah.",
    },
    m0b_BebYNBQ: {
      title: "Baby Cobra",
      description: "Regangan belakang yang lembut yang membuka dada dan mengukuhkan belakang atas sambil menggalakkan mobiliti tulang belakang.",
    },
    hComtEvbgN4: {
      title: "Posisi Lapan Titik",
      description: "Posisi menurun terkawal di mana lapan titik badan menyentuh lantai, membantu mengukuhkan lengan, bahu, dada, dan teras.",
    },
    "Ma93Zxwp_-o": {
      title: "Plank",
      description: "Posisi kekuatan seluruh badan yang melibatkan teras, bahu, lengan, dan kaki sambil membina kestabilan dan kawalan badan.",
    },
    "0MUxqZmmmq8": {
      title: "Downward Dog",
      description: "Regangan seluruh badan yang memanjangkan tulang belakang, bahu, hamstring, dan betis sambil mengukuhkan bahagian atas badan.",
    },
    ze9cJVnkYOg: {
      title: "Posisi Segitiga",
      description: "Regangan berdiri yang membuka pinggul dan dada sambil memanjangkan sisi badan dan meningkatkan keseimbangan.",
    },
    "aP40k--wiPo": {
      title: "Posisi Sudut Sisi",
      description: "Regangan berdiri yang mendalam yang mengukuhkan kaki sambil membuka pinggul, dada, bahu, dan sisi badan.",
    },
    "1EmtCVdAKuI": {
      title: "Reverse Warrior 2",
      description: "Regangan sisi mengalir daripada Warrior 2 yang membuka rusuk dan pinggang sambil mengekalkan kekuatan dan kestabilan kaki.",
    },
    D8OEOqj6LKo: {
      title: "Warrior 2",
      description: "Posisi berdiri yang kukuh yang membina daya tahan kaki dan mobiliti pinggul sambil membuka dada dan meningkatkan keseimbangan.",
    },
    ETFrnz9CCsw: {
      title: "Warrior 1",
      description: "Posisi berdiri yang kukuh yang mengukuhkan kaki sambil meregangkan pinggul dan membuka dada dan bahu.",
    },
    vpECbuWGnVw: {
      title: "Warrior 3",
      description: "Keseimbangan satu kaki yang mencabar kestabilan sambil mengukuhkan kaki, teras, belakang, dan punggung.",
    },
    "zr-EsTGQE3g": {
      title: "Standing Crunch",
      description: "Pergerakan teras yang dilakukan sambil berdiri, menyatukan bahagian atas dan bawah badan, mengaktifkan otot abdomen sambil meningkatkan koordinasi dan keseimbangan.",
    },
    qJHd5KIO35I: {
      title: "Regangan Belakang dan Dada",
      description: "Regangan mobiliti yang membuka dada dan bahu sambil melegakan ketegangan pada belakang atas.",
    },
    Z_LIRhABH7c: {
      title: "Posisi Goddess (Regangan Kaki)",
      description: "Squat berdiri luas yang membuka pinggul dan bahagian dalam paha sambil mengukuhkan punggung, paha, dan kaki.",
    },
    r4ixF0BmzfI: {
      title: "Posisi Goddess (Putaran Bahu dan Badan)",
      description: "Posisi Goddess digabungkan dengan putaran bahagian atas badan untuk meregangkan bahu dan tulang belakang sambil mengekalkan kekuatan bahagian bawah badan.",
    },
    "78t9qqSWf4Q": {
      title: "Angkatan Kaki (Lurus)",
      description: "Angkatan kaki lurus yang terkawal yang mengukuhkan otot fleksor pinggul dan teras sambil membantu meningkatkan mobiliti bahagian bawah badan.",
    },
    "6tlBgzidSuU": {
      title: "Angkatan Kaki (Bengkok)",
      description: "Angkatan kaki dengan lutut bengkok yang mengaktifkan otot teras dan pinggul dengan julat pergerakan yang lebih terkawal dan mudah diikuti.",
    },
    "vkb-jrEq4sc": {
      title: "Putaran Bahu dan Badan",
      description: "Regangan putaran yang menggerakkan tulang belakang sambil melegakan ketegangan pada bahu, dada, dan belakang atas.",
    },
    "5jSzGqTOTeY": {
      title: "Regangan Sisi Bahu",
      description: "Regangan lengkung sisi yang memanjangkan bahu, belakang atas, pinggang, dan sisi badan.",
    },
    "-K7puFfQgIc": {
      title: "Putaran Lengan Bengkok",
      description: "Pergerakan mobiliti bahu menggunakan lengan bengkok untuk memutarkan sendi bahu dengan lembut dan melonggarkan bahagian atas badan.",
    },
    oCGcR5GgpWI: {
      title: "Putaran Lengan Lurus",
      description: "Putaran lengan terkawal yang bergerak melalui julat pergerakan bahu yang lebih luas untuk meningkatkan mobiliti dan memanaskan bahu.",
    },
    ZhelQy85j3M: {
      title: "Regangan Kepala, Leher dan Bahu",
      description: "Urutan mobiliti yang lembut direka untuk melegakan ketegangan di sekitar leher, bahu, dan belakang atas sambil meningkatkan julat pergerakan yang selesa.",
    },
  },
  ta: {
    egNdbDDS_Ws: { title: "நேர்காணல் 01 — A/Prof CK Seow" },
    dyYVJnccUx0: { title: "நேர்காணல் 02 — A/Prof CK Seow" },
    IsGAZrjEMp4: { title: "நேர்காணல் 03 — Ms LP Lim" },
    jV6KZ2no0Pg: { title: "நேர்காணல் 02 — Ms LP Lim" },
    CiJ0R9ZugeY: { title: "நேர்காணல் 01 — Ms LP Lim" },
    mzqsdpvfDto: {
      title: "சூரிய நமஸ்கார ஓட்டம்",
      description: "மூச்சையும் இயக்கத்தையும் இணைக்கும் ஒரு ஆற்றல்மிக்க வரிசை, இது நெகிழ்வுத்தன்மை, மூட்டு இயக்கம், மற்றும் இரத்த ஓட்டத்தை மேம்படுத்தும் அதே வேளையில் உடல் முழுவதையும் சூடேற்றுகிறது.",
    },
    m0b_BebYNBQ: {
      title: "பேபி கோப்ரா",
      description: "மார்பைத் திறந்து, மேல் முதுகை வலுப்படுத்தும் ஒரு மென்மையான பின்வளைவு தோரணை, இது முதுகெலும்பு இயக்கத்தையும் ஊக்குவிக்கிறது.",
    },
    hComtEvbgN4: {
      title: "எட்டு புள்ளி தோரணை",
      description: "உடலின் எட்டு புள்ளிகள் தரையைத் தொடும் ஒரு கட்டுப்படுத்தப்பட்ட தாழ்வு நிலை, இது கைகள், தோள்பட்டைகள், மார்பு, மற்றும் மைய தசைகளை வலுப்படுத்த உதவுகிறது.",
    },
    "Ma93Zxwp_-o": {
      title: "பிளாங்க்",
      description: "மையம், தோள்பட்டைகள், கைகள், மற்றும் கால்களை ஈடுபடுத்தி, உறுதித்தன்மையையும் உடல் கட்டுப்பாட்டையும் உருவாக்கும் ஒரு முழு உடல் பலத் தோரணை.",
    },
    "0MUxqZmmmq8": {
      title: "டவுன்வர்ட் டாக்",
      description: "முதுகெலும்பு, தோள்பட்டைகள், தொடைப் பின்புறம், மற்றும் கெண்டைக்காலை நீட்டி, மேல் உடலை வலுப்படுத்தும் ஒரு முழு உடல் நீட்சி தோரணை.",
    },
    ze9cJVnkYOg: {
      title: "முக்கோண தோரணை",
      description: "இடுப்பையும் மார்பையும் திறந்து, உடலின் பக்கவாட்டை நீட்டி, சமநிலையை மேம்படுத்தும் ஒரு நின்று செய்யும் நீட்சி தோரணை.",
    },
    "aP40k--wiPo": {
      title: "பக்க கோண தோரணை",
      description: "கால்களை வலுப்படுத்தும் அதே வேளையில், இடுப்பு, மார்பு, தோள்பட்டைகள், மற்றும் உடலின் பக்கவாட்டைத் திறக்கும் ஒரு ஆழமான நின்று செய்யும் நீட்சி தோரணை.",
    },
    "1EmtCVdAKuI": {
      title: "தலைகீழ் வாரியர் 2",
      description: "வாரியர் 2-லிருந்து ஓடும் ஒரு பக்க நீட்சி, இது கால்களின் பலத்தையும் உறுதித்தன்மையையும் பேணி, விலா எலும்புகளையும் இடுப்பையும் திறக்கிறது.",
    },
    D8OEOqj6LKo: {
      title: "வாரியர் 2",
      description: "கால் சகிப்புத்தன்மையையும் இடுப்பு இயக்கத்தையும் வளர்க்கும் அதே வேளையில், மார்பைத் திறந்து சமநிலையை மேம்படுத்தும் ஒரு வலுவான நின்று செய்யும் தோரணை.",
    },
    ETFrnz9CCsw: {
      title: "வாரியர் 1",
      description: "கால்களை வலுப்படுத்தும் அதே வேளையில், இடுப்பை நீட்டி மார்பையும் தோள்பட்டைகளையும் திறக்கும் ஒரு ஆற்றல்மிக்க நின்று செய்யும் தோரணை.",
    },
    vpECbuWGnVw: {
      title: "வாரியர் 3",
      description: "கால்கள், மையம், முதுகு, மற்றும் இடுப்புத் தசைகளை வலுப்படுத்தும் அதே வேளையில், உறுதித்தன்மையைச் சவால் செய்யும் ஒற்றைக்கால் சமநிலை தோரணை.",
    },
    "zr-EsTGQE3g": {
      title: "நின்று செய்யும் கிரஞ்ச்",
      description: "மேல் மற்றும் கீழ் உடலை ஒன்றிணைத்து, ஒருங்கிணைப்பையும் சமநிலையையும் மேம்படுத்தும் அதே வேளையில், வயிற்றுத் தசைகளைச் செயல்படுத்தும் ஒரு நின்று செய்யும் மைய இயக்கம்.",
    },
    qJHd5KIO35I: {
      title: "முதுகு மற்றும் மார்பு நீட்சி",
      description: "மார்பையும் தோள்பட்டைகளையும் திறந்து, மேல் முதுகின் இறுக்கத்தை நீக்கும் ஒரு இயக்க நீட்சி தோரணை.",
    },
    Z_LIRhABH7c: {
      title: "காடஸ் தோரணை (கால் நீட்சி)",
      description: "புட்டம், தொடை, மற்றும் கால்களை வலுப்படுத்தும் அதே வேளையில், இடுப்பையும் தொடையின் உள்பகுதியையும் திறக்கும் ஒரு அகன்ற நிலை குந்து தோரணை.",
    },
    r4ixF0BmzfI: {
      title: "காடஸ் தோரணை (தோள் மற்றும் உடல் திருப்பம்)",
      description: "கீழ் உடலின் பலத்தைப் பேணும் அதே வேளையில், தோள்பட்டைகளையும் முதுகெலும்பையும் நீட்டும் வகையில், காடஸ் நிலையுடன் மேல் உடல் சுழற்சியை இணைக்கும் தோரணை.",
    },
    "78t9qqSWf4Q": {
      title: "கால் தூக்கல் (நேரான)",
      description: "இடுப்பு ஃபிளெக்சர் தசைகளையும் மையத்தையும் வலுப்படுத்தும் அதே வேளையில், கீழ் உடல் இயக்கத்தை மேம்படுத்த உதவும் ஒரு கட்டுப்படுத்தப்பட்ட நேரான கால் தூக்கல்.",
    },
    "6tlBgzidSuU": {
      title: "கால் தூக்கல் (மடிந்த)",
      description: "மையம் மற்றும் இடுப்புத் தசைகளைச் செயல்படுத்தும், மேலும் கட்டுப்படுத்தப்பட்ட மற்றும் எளிதாகப் பின்பற்றக்கூடிய இயக்க வீச்சைக் கொண்ட ஒரு மடிந்த முழங்கால் கால் தூக்கல்.",
    },
    "vkb-jrEq4sc": {
      title: "தோள் மற்றும் உடல் திருப்பம்",
      description: "தோள்பட்டைகள், மார்பு, மற்றும் மேல் முதுகின் இறுக்கத்தை நீக்கும் அதே வேளையில், முதுகெலும்பை இயக்கும் ஒரு சுழற்சி நீட்சி.",
    },
    "5jSzGqTOTeY": {
      title: "தோள் பக்கவாட்டு நீட்சி",
      description: "தோள்பட்டைகள், மேல் முதுகு, இடுப்பு, மற்றும் உடலின் பக்கவாட்டை நீட்டும் ஒரு பக்கவாட்டு வளைவு நீட்சி.",
    },
    "-K7puFfQgIc": {
      title: "மடிந்த கை சுழற்சி",
      description: "மடிந்த கைகளைப் பயன்படுத்தி தோள் மூட்டுகளை மென்மையாகச் சுழற்றி, மேல் உடலைத் தளர்த்தும் ஒரு தோள் இயக்க பயிற்சி.",
    },
    oCGcR5GgpWI: {
      title: "நேரான கை சுழற்சி",
      description: "தோள் இயக்கத்தை மேம்படுத்தவும் தோள்பட்டைகளைச் சூடேற்றவும், பரந்த தோள் இயக்க வீச்சின் வழியாகச் செயல்படும் ஒரு கட்டுப்படுத்தப்பட்ட கை சுழற்சி.",
    },
    ZhelQy85j3M: {
      title: "தலை, கழுத்து மற்றும் தோள் நீட்சி",
      description: "கழுத்து, தோள்பட்டைகள், மற்றும் மேல் முதுகைச் சுற்றியுள்ள இறுக்கத்தை நீக்கி, வசதியான இயக்க வீச்சை மேம்படுத்தும் வகையில் வடிவமைக்கப்பட்ட ஒரு மென்மையான இயக்க வரிசை.",
    },
  },
};
